publiclab/leaflet-blurred-location

spec/javascripts/test_spec.js
src/object.js

fixes #6 (edit by @jywarren to associate with the related issue)

Added the function addGrid to locationForm.js

---

Gruntfile.js
dist/Leaflet.BlurredLocation.js
examples/index.html
src/core/addGrid.js
src/core/object.js

Hi, @mridulnagpal! Check it out -- not such big changes, but I realize you were requiring in `addGrid` but not actually running it. I also changed some spacing and indentation (fixing part of #15) and unplugged the `getPlacenameFromCoordinates()` reference (used to have different name) from `addGrid.js`. 
I think we need to restructure `addGrid` to have submethods, so we can do (proposing a renaming too):
```js
gridSystem = require('./GridSystem.js');
gridSystem.setup(options.map);
gridSystem.disable(); // turns off the grid! Could also be .remove()
```
If we create this submodule called `GridSystem` whose purpose is only to draw a grid, we can test that it's doing so, and leave it at that -- we no longer have to deal with the complexity in there.

got addGrid to run

---

spec/javascripts/test_spec.js

Spec description added

---

package.json

I wasn't sure this was required, so just testing it out...

remove phantom-jasmine

---

dist/Leaflet.BlurredLocation.js
spec/javascripts/test_spec.js
src/blurredLocation.js

Test for truncate added

---

dist/Leaflet.BlurredLocation.js
examples/index.html
src/blurredLocation.js
src/ui/Interface.js

Obscure moved to interface

---

dist/Leaflet.BlurredLocation.js
spec/javascripts/ui_spec.js
src/blurredLocation.js
src/ui/Interface.js

onDrag method added

---

dist/Leaflet.BlurredLocation.js
examples/index.html
src/blurredLocation.js
src/ui/Interface.js

In this PR when we enter a location to input listener with default ID 'geo_location' (Can be set using options) the map pans to the entered location and the lat and lng are displayed in their respective boxes.

geocode shifted and working

---

examples/index.html

Hi, @mridulnagpal -- I reworked the example HTML to make it a bit more readable and nice looking, and added some explanatory text and a credit line. Hope this looks OK to you!

example restyling and extra info

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js

touch gesture fix

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js

Location linted and proofed

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js

Take Map ID as input

---

package.json

Corrected the name of the library along with repo URL's and everything.

npm specifications corrected

---

dist/Leaflet.BlurredLocation.js
examples/index.html
src/blurredLocation.js

Here is the button and the implementation of the displayLocation function according to the latest codebase.

Implementation of a button to display current latitude and longitude

---

README.md

Fixed readme issue #91

---

dist/Leaflet.BlurredLocation.js
package.json
src/blurredLocation.js

No more inv lat lng

---

README.md

Contribution docs added

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js

Bounding box for precision -1

---

examples/index.html

Input with 'Get my location' in demo is changed with button.

Change input to button

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js
src/ui/Interface.js

UI precision

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js

Blur checkbox

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js

re-calculate coordinates when changing isBlurred #105

---

dist/Leaflet.BlurredLocation.js
src/blurredLocation.js
src/core/Geocoding.js

In continuation with code separation

Two more methods separated

---

examples/index.html

Fixes #146 @mridulnagpal -- check it out!

Slider fixes

---

examples/index.html

added  link of publiclab.org

---

dist/Leaflet.BlurredLocation.js
examples/index.html
package.json
src/blurredLocation.js

Hi @jywarren ! 
In this PR , i aim to make some listeners optional , as these would be most probably not always required when we will integrate LBLD to plots2 and other places 😄 !
Kindly publish this to **NPM** also 📦 .

Make blurry scale display optional !

---

CODE_OF_CONDUCT.md

Fixes #166 
Please review the added code of conduct file.

Code of Conduct Added.

---

src/core/Geocoding.js

Removing console.log snippet as requested.

Removing Geocode log

---

dist/Leaflet.BlurredLocation.js
package.json
src/core/Geocoding.js

Fixes https://github.com/publiclab/PublicLab.Editor/issues/281 !

"Use current location" button used to remove all <i> tags .

---

src/core/Geocoding.js

Update gh-pages branch with google geometry API.

change geometry location on gh-pages

---

examples/index.html

Update slider when map is zoomed in and out

---

dist/Leaflet.BlurredLocation.js
src/core/Geocoding.js

[Demo](https://streamable.com/hl8yz)
On the demo, you can't see me clicking "Don't allow" on Firefox popup, my screen recorder doesn't capture them for some reason. You can see me moving the cursor from the button and clicking on "empty page", but it's actually Don't allow" button on the popup.
Resolves https://github.com/publiclab/plots2/issues/7305

FIX: Auto-locate me button multiple spinners

---

dist/Leaflet.BlurredLocation.js
package.json
src/blurredLocation.js

Fixes https://github.com/publiclab/leaflet-blurred-location/issues/259

Update MapBox API tile source
